// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NodeExecution struct {
	ID            pgtype.UUID
	WorkflowRunID pgtype.UUID
	NodeID        string
	Status        string
	InputData     []byte
	OutputData    []byte
	Error         pgtype.Text
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Schedule struct {
	ID         pgtype.UUID
	WorkflowID pgtype.UUID
	CronExpr   string
	Payload    []byte
	Enabled    bool
	LastRunAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Workflow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Definition  []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type WorkflowRun struct {
	ID          pgtype.UUID
	WorkflowID  pgtype.UUID
	Status      string
	InputData   []byte
	OutputData  []byte
	Error       pgtype.Text
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
