// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNodeExecution = `-- name: CreateNodeExecution :one
INSERT INTO node_executions (
    id, workflow_run_id, node_id, status, input_data
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, workflow_run_id, node_id, status, input_data, output_data, error, started_at, completed_at, created_at
`

type CreateNodeExecutionParams struct {
	ID            pgtype.UUID
	WorkflowRunID pgtype.UUID
	NodeID        string
	Status        string
	InputData     []byte
}

func (q *Queries) CreateNodeExecution(ctx context.Context, arg CreateNodeExecutionParams) (NodeExecution, error) {
	row := q.db.QueryRow(ctx, createNodeExecution,
		arg.ID,
		arg.WorkflowRunID,
		arg.NodeID,
		arg.Status,
		arg.InputData,
	)
	var i NodeExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.NodeID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (
    id, name, description, definition
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, description, definition, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Definition  []byte
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Definition,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (
    id, workflow_id, status, input_data
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, workflow_id, status, input_data, output_data, error, started_at, completed_at, created_at
`

type CreateWorkflowRunParams struct {
	ID         pgtype.UUID
	WorkflowID pgtype.UUID
	Status     string
	InputData  []byte
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.ID,
		arg.WorkflowID,
		arg.Status,
		arg.InputData,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const failRunsExceedingDuration = `-- name: FailRunsExceedingDuration :execrows
UPDATE workflow_runs
SET status = 'failed',
    error = $1,
    completed_at = NOW()
WHERE status = 'running'
  AND started_at < $2
`

type FailRunsExceedingDurationParams struct {
	Error     pgtype.Text
	StartedAt pgtype.Timestamptz
}

func (q *Queries) FailRunsExceedingDuration(ctx context.Context, arg FailRunsExceedingDurationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failRunsExceedingDuration, arg.Error, arg.StartedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStaleRuns = `-- name: FailStaleRuns :execrows
UPDATE workflow_runs
SET status = 'failed',
    error = $1,
    completed_at = NOW()
WHERE status IN ('running', 'pending')
`

func (q *Queries) FailStaleRuns(ctx context.Context, error pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleRuns, error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNodeExecution = `-- name: GetNodeExecution :one
SELECT id, workflow_run_id, node_id, status, input_data, output_data, error, started_at, completed_at, created_at FROM node_executions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNodeExecution(ctx context.Context, id pgtype.UUID) (NodeExecution, error) {
	row := q.db.QueryRow(ctx, getNodeExecution, id)
	var i NodeExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.NodeID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, name, description, definition, created_at, updated_at FROM workflows
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, workflow_id, status, input_data, output_data, error, started_at, completed_at, created_at FROM workflow_runs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNodeExecutionsForRun = `-- name: ListNodeExecutionsForRun :many
SELECT id, workflow_run_id, node_id, status, input_data, output_data, error, started_at, completed_at, created_at FROM node_executions
WHERE workflow_run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListNodeExecutionsForRun(ctx context.Context, workflowRunID pgtype.UUID) ([]NodeExecution, error) {
	rows, err := q.db.Query(ctx, listNodeExecutionsForRun, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeExecution
	for rows.Next() {
		var i NodeExecution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.NodeID,
			&i.Status,
			&i.InputData,
			&i.OutputData,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNodeExecutions = `-- name: ListPendingNodeExecutions :many
SELECT id, workflow_run_id, node_id, status, input_data, output_data, error, started_at, completed_at, created_at FROM node_executions
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingNodeExecutions(ctx context.Context, limit int32) ([]NodeExecution, error) {
	rows, err := q.db.Query(ctx, listPendingNodeExecutions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeExecution
	for rows.Next() {
		var i NodeExecution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.NodeID,
			&i.Status,
			&i.InputData,
			&i.OutputData,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, workflow_id, status, input_data, output_data, error, started_at, completed_at, created_at FROM workflow_runs
WHERE workflow_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkflowRunsParams struct {
	WorkflowID pgtype.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns, arg.WorkflowID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Status,
			&i.InputData,
			&i.OutputData,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, description, definition, created_at, updated_at FROM workflows
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWorkflowsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeExecutionStatus = `-- name: UpdateNodeExecutionStatus :one
UPDATE node_executions
SET status = $2,
    output_data = COALESCE($3, output_data),
    error = COALESCE($4, error),
    started_at = COALESCE($5, started_at),
    completed_at = COALESCE($6, completed_at)
WHERE id = $1
RETURNING id, workflow_run_id, node_id, status, input_data, output_data, error, started_at, completed_at, created_at
`

type UpdateNodeExecutionStatusParams struct {
	ID          pgtype.UUID
	Status      string
	OutputData  []byte
	Error       pgtype.Text
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) UpdateNodeExecutionStatus(ctx context.Context, arg UpdateNodeExecutionStatusParams) (NodeExecution, error) {
	row := q.db.QueryRow(ctx, updateNodeExecutionStatus,
		arg.ID,
		arg.Status,
		arg.OutputData,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i NodeExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.NodeID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET name        = $2,
    description = $3,
    definition  = $4,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, description, definition, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Definition  []byte
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Definition,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflowRunStatus = `-- name: UpdateWorkflowRunStatus :one
UPDATE workflow_runs
SET status = $2,
    output_data = COALESCE($3, output_data),
    error = COALESCE($4, error),
    started_at = COALESCE($5, started_at),
    completed_at = COALESCE($6, completed_at)
WHERE id = $1
RETURNING id, workflow_id, status, input_data, output_data, error, started_at, completed_at, created_at
`

type UpdateWorkflowRunStatusParams struct {
	ID          pgtype.UUID
	Status      string
	OutputData  []byte
	Error       pgtype.Text
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) UpdateWorkflowRunStatus(ctx context.Context, arg UpdateWorkflowRunStatusParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRunStatus,
		arg.ID,
		arg.Status,
		arg.OutputData,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
